-- Database Schema Setup
-- This script sets up the database tables, policies, and realtime configuration.
-- It consolidates the participants and sessions tables setup.

-- ==========================================
-- 1. Create Tables
-- ==========================================

-- Create sessions table
CREATE TABLE IF NOT EXISTS public.sessions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN DEFAULT true
);

-- Enable Row Level Security (RLS) for sessions
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Create policies for sessions
CREATE POLICY "Allow public read access to sessions"
ON public.sessions FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow public insert access to sessions"
ON public.sessions FOR INSERT
TO anon, authenticated
WITH CHECK (true);


-- Create participants table
-- Note: id is TEXT to support custom IDs generated by the frontend importer
CREATE TABLE IF NOT EXISTS public.participants (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE
);

-- Create index for faster lookups on session_id
CREATE INDEX IF NOT EXISTS idx_participants_session_id ON public.participants(session_id);

-- Enable Row Level Security (RLS) for participants
ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;

-- Enable Realtime for the participants table
ALTER PUBLICATION supabase_realtime ADD TABLE public.participants;

-- ==========================================
-- 2. Policies
-- ==========================================

-- Policies for participants
CREATE POLICY "Allow public read access" 
  ON public.participants 
  FOR SELECT 
  TO anon, authenticated
  USING (true);

CREATE POLICY "Allow public insert access" 
  ON public.participants 
  FOR INSERT 
  TO anon, authenticated
  WITH CHECK (true);

-- ==========================================
-- 3. Grants
-- ==========================================

-- Grant access to the anon and authenticated roles
GRANT SELECT, INSERT ON public.participants TO anon;
GRANT SELECT, INSERT ON public.participants TO authenticated;
GRANT SELECT, INSERT ON public.sessions TO anon;
GRANT SELECT, INSERT ON public.sessions TO authenticated;
